
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<GreetResponse> {
    return await TAURI_INVOKE("greet", { name });
},
async loadCollection(path: string) : Promise<Result<CollectionManifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_collection", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkspace(path: string) : Promise<Result<WorkspaceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthRef = ({ [key in string]: string }) & { type: string }
/**
 * Represents the structure of a `cortex.yaml` collection manifest file.
 */
export type CollectionManifest = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the collection
 */
name: string; 
/**
 * Optional description of the collection
 */
description?: string | null; 
/**
 * Default authentication settings for all requests in the collection
 */
auth?: AuthRef | null; 
/**
 * Default headers for all requests in the collection
 */
headers?: { [key in string]: string } | null; 
/**
 * Collection-level variables
 */
variables?: { [key in string]: string } | null }
export type GreetResponse = { message: string }
export type WorkspaceCollectionResult = { path: string; name: string | null; error: string | null }
export type WorkspaceResponse = { name: string; collections: WorkspaceCollectionResult[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
