
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<GreetResponse> {
    return await TAURI_INVOKE("greet", { name });
},
async loadCollection(path: string) : Promise<Result<Collection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_collection", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRequest(request: RequestFile, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_request", { request, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRequest(name: string, parentPath: string, method: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_request", { name, parentPath, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteItem(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_item", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameItem(path: string, newName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_item", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveItem(path: string, newParent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_item", { path, newParent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(name: string, parentPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { name, parentPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateRequest(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_request", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openInExplorer(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_explorer", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkspace(path: string) : Promise<Result<WorkspaceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(name: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeWorkspace() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCollectionToWorkspace(workspacePath: string, collectionPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_collection_to_workspace", { workspacePath, collectionPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCollectionFromWorkspace(workspacePath: string, collectionPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_collection_from_workspace", { workspacePath, collectionPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastWorkspacePath() : Promise<string | null> {
    return await TAURI_INVOKE("get_last_workspace_path");
},
async getRecentWorkspaces() : Promise<RecentWorkspace[]> {
    return await TAURI_INVOKE("get_recent_workspaces");
},
/**
 * Returns "workspace", "collection", or "unknown" for a given directory path.
 */
async detectDirectoryType(path: string) : Promise<string> {
    return await TAURI_INVOKE("detect_directory_type", { path });
},
async getAppSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_app_settings");
},
async pickFile(title: string, filterName: string, filterExt: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_file", { title, filterName, filterExt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickDirectory(title: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_directory", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveFile(title: string, filterName: string, filterExt: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_file", { title, filterName, filterExt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(name: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorkspaceVariables(workspacePath: string, variables: Variable[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workspace_variables", { workspacePath, variables }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollectionVariables(collectionPath: string, variables: Variable[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection_variables", { collectionPath, variables }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollectionAuth(collectionPath: string, auth: AuthRef | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection_auth", { collectionPath, auth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFolderAuth(folderPath: string, auth: AuthRef | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_folder_auth", { folderPath, auth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollectionHeaders(collectionPath: string, headers: { [key in string]: string } | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection_headers", { collectionPath, headers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFolderHeaders(folderPath: string, headers: { [key in string]: string } | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_folder_headers", { folderPath, headers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEnvironmentVariables(workspacePath: string, environmentName: string, variables: Variable[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_environment_variables", { workspacePath, environmentName, variables }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEnvironment(workspacePath: string, environmentName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_environment", { workspacePath, environmentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getResolvedVariables(workspacePath: string | null, collectionPath: string | null, environmentName: string | null) : Promise<Result<{ [key in string]: ResolvedVariable }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_resolved_variables", { workspacePath, collectionPath, environmentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewTemplate(text: string, workspacePath: string | null, collectionPath: string | null, environmentName: string | null) : Promise<Result<PreviewResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_template", { text, workspacePath, collectionPath, environmentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCollectionManifest(path: string) : Promise<Result<Collection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_collection_manifest", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkspaceManifest(path: string) : Promise<Result<WorkspaceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workspace_manifest", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all current ephemeral variables ordered by name.
 * The store lives only for the duration of the process — closing the app clears it.
 */
async getEphemeralVariables() : Promise<Variable[]> {
    return await TAURI_INVOKE("get_ephemeral_variables");
},
/**
 * Atomically replaces the entire ephemeral variable set.
 * Used by the variable panel "Save Changes" action for the Session scope.
 */
async setEphemeralVariables(variables: Variable[]) : Promise<void> {
    await TAURI_INVOKE("set_ephemeral_variables", { variables });
},
/**
 * Upserts a single ephemeral variable by name.
 * Intended for script use — allows runtime injection of one-time values.
 */
async setEphemeralVariable(name: string, value: JsonValue, secret: boolean) : Promise<void> {
    await TAURI_INVOKE("set_ephemeral_variable", { name, value, secret });
},
/**
 * Removes a single ephemeral variable by name.
 * Intended for script use.
 */
async removeEphemeralVariable(name: string) : Promise<void> {
    await TAURI_INVOKE("remove_ephemeral_variable", { name });
},
/**
 * Returns all enabled prompt variables from the given collection / environment
 * that do not yet have a runtime (ephemeral) override in the current session.
 * 
 * The frontend calls this before starting a collection run to determine which
 * variables still need user input.
 */
async getPromptVariables(collectionPath: string, environmentName: string | null) : Promise<Result<Variable[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompt_variables", { collectionPath, environmentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendRequest(payload: SendRequestPayload, metadata: RequestMetadata) : Promise<Result<RequestHistoryEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_request", { payload, metadata }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRequestHistory() : Promise<RequestHistoryEntry[]> {
    return await TAURI_INVOKE("get_request_history");
},
async clearRequestHistory() : Promise<void> {
    await TAURI_INVOKE("clear_request_history");
},
async previewRequestHeaders(headers: HeaderEntry[], workspacePath: string | null, collectionPath: string | null, environmentName: string | null, requestPath: string | null) : Promise<Result<PreviewHeadersResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_request_headers", { headers, workspacePath, collectionPath, environmentName, requestPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async introspectGraphql(payload: IntrospectionPayload, workspacePath: string | null, collectionPath: string | null, environmentName: string | null, requestPath: string | null) : Promise<Result<RequestHistoryEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("introspect_graphql", { payload, workspacePath, collectionPath, environmentName, requestPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveEnvironment(name: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_environment", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRequest(requestId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_request", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauth2FetchToken(payload: OAuth2FetchPayload) : Promise<Result<{ [key in string]: string }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth2_fetch_token", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async oauth2RefreshToken(payload: OAuth2RefreshPayload) : Promise<Result<{ [key in string]: string }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth2_refresh_token", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { last_workspace_path: string | null; recent_workspaces?: RecentWorkspace[]; active_environment: string | null; timeout?: number; redirect_behavior?: string }
export type AuthRef = ({ [key in string]: string }) & { type: string }
/**
 * Represents a loaded collection.
 */
export type Collection = { path: string; manifest: CollectionManifest; items: CollectionItem[] }
export type CollectionItem = { type: "Request"; data: RequestFileWrapper } | { type: "Folder"; data: Folder }
/**
 * Represents the structure of a `cortex.yaml` collection manifest file.
 */
export type CollectionManifest = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the collection
 */
name: string; 
/**
 * Optional description of the collection
 */
description?: string | null; 
/**
 * Default authentication settings for all requests in the collection
 */
auth?: AuthRef | null; 
/**
 * Default headers for all requests in the collection
 */
headers?: { [key in string]: string } | null; 
/**
 * Collection-level variables
 */
variables?: Variable[] | null }
export type EnvironmentFile = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the environment
 */
name: string; 
/**
 * List of environment variables
 */
variables: Variable[] }
export type Folder = { name: string; path: string; relative_path: string; manifest?: FolderManifest | null; items: CollectionItem[] }
/**
 * Represents the optional `folder.yaml` configuration inside a folder directory.
 */
export type FolderManifest = { headers?: { [key in string]: string } | null; auth?: AuthRef | null }
export type FormEntry = { key: string; value: string; is_file: boolean; file_path: string; enabled: boolean }
export type GreetResponse = { message: string }
export type HeaderEntry = { key: string; value: string; enabled: boolean; is_valueless?: boolean | null }
export type IntrospectionPayload = { endpoint_url: string; headers: HeaderEntry[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type OAuth2FetchPayload = { grantType: string; tokenEndpoint: string | null; authEndpoint: string | null; clientId: string | null; clientSecret: string | null; scope: string | null; username: string | null; password: string | null; additionalParams: string | null; redirectUriMode: string | null; customRedirectUri: string | null; workspacePath: string | null; collectionPath: string | null; environmentName: string | null }
export type OAuth2RefreshPayload = { refreshToken: string; tokenEndpoint: string; clientId: string; clientSecret: string | null; additionalParams: string | null; workspacePath: string | null; collectionPath: string | null; environmentName: string | null }
export type PreviewHeadersResponse = { headers: RenderedHeader[]; warnings: string[] }
export type PreviewResponse = { text: string; warnings: UnresolvedVariableWarning[]; syntax_errors: TemplateSyntaxError[]; captured_variables: { [key in string]: string } }
export type RecentWorkspace = { name: string; path: string }
export type RedirectHop = { method: string; url: string; status_code: number }
export type RenderedHeader = { key: string; value: string }
export type RequestBody = { text?: string | null; json?: string | null; form?: { [key in string]: string } | null; active_type?: string | null; raw_text?: string | null; raw_subtype?: string | null; form_data?: FormEntry[] | null; url_encoded?: UrlEncodedEntry[] | null; file_path?: string | null; file_filter?: string | null }
/**
 * Represents the structure of a `.crx` request file.
 */
export type RequestFile = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the request
 */
name: string; 
/**
 * HTTP method (e.g., GET, POST, PUT, DELETE)
 */
method: string; 
/**
 * Request URL (may contain environment variables)
 */
url: string; 
/**
 * HTTP headers
 */
headers?: { [key in string]: string } | null; 
/**
 * Query parameters
 */
params?: { [key in string]: string } | null; 
/**
 * Request body
 */
body?: RequestBody | null; 
/**
 * Authentication configuration
 */
auth?: AuthRef | null; 
/**
 * Pre-request and post-response scripts
 */
scripts?: Scripts | null; 
/**
 * Test scripts
 */
tests?: string | null; 
/**
 * Tags for categorization
 */
tags?: string[] | null; 
/**
 * Per-request settings
 */
settings?: Settings | null }
export type RequestFileWrapper = { name: string; path: string; relative_path: string; content: RequestFile | null; error: string | null }
/**
 * Represents an executed request log entry captured in history.
 */
export type RequestHistoryEntry = { id: string; request_name: string; method: string; raw_url: string; rendered_url: string; 
/**
 * Variables resolved and captured during execution/rendering
 */
captured_variables: { [key in string]: string }; executed_at: string; duration_ms: number | null; status_code: number | null; status_text: string | null; response_body: string | null; headers?: { [key in string]: string }; error: string | null; warnings?: string[]; redirect_chain?: RedirectHop[] }
export type RequestMetadata = { workspace_path: string | null; collection_path: string | null; environment_name: string | null; request_path: string | null }
export type ResolvedVariable = { value: JsonValue; scope: VariableScope; secret: boolean; description?: string | null }
export type Scripts = { pre?: string | null; post?: string | null }
export type SendRequestPayload = { request_id: string; request_name: string; method: string; url: string; headers: HeaderEntry[]; auth: AuthRef | null; body: RequestBody | null; settings: Settings | null }
export type Settings = { timeout?: string | null; redirect_behavior?: string | null }
/**
 * A template syntax error encountered during parsing or rendering.
 */
export type TemplateSyntaxError = { 
/**
 * The offending raw text (e.g. `"{{unclosed"`).
 */
raw: string; 
/**
 * Human-readable description of the problem.
 */
message: string }
export type UnresolvedVariableWarning = { name: string }
export type UrlEncodedEntry = { key: string; value: string; enabled: boolean }
export type Variable = { name: string; value: JsonValue; secret?: boolean; enabled?: boolean; 
/**
 * If true, the user is asked to supply a value before each collection run.
 * The `value` field serves as the pre-filled default shown in the prompt dialog.
 */
prompt?: boolean; 
/**
 * Optional hint shown beneath the input in the prompt dialog.
 */
description?: string | null }
export type VariableScope = "global" | "collection" | "environment" | "runtime" | "dynamic"
export type WorkspaceCollectionResult = { path: string; name: string | null; error: string | null }
export type WorkspaceResponse = { name: string; collections: WorkspaceCollectionResult[]; variables: Variable[] | null; environments: EnvironmentFile[]; active_environment: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
