
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<GreetResponse> {
    return await TAURI_INVOKE("greet", { name });
},
async loadCollection(path: string) : Promise<Result<Collection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_collection", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRequest(request: RequestFile, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_request", { request, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRequest(name: string, parentPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_request", { name, parentPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteItem(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_item", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameItem(path: string, newName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_item", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveItem(path: string, newParent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_item", { path, newParent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkspace(path: string) : Promise<Result<WorkspaceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(name: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCollectionToWorkspace(workspacePath: string, collectionPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_collection_to_workspace", { workspacePath, collectionPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCollectionFromWorkspace(workspacePath: string, collectionPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_collection_from_workspace", { workspacePath, collectionPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastWorkspacePath() : Promise<string | null> {
    return await TAURI_INVOKE("get_last_workspace_path");
},
async pickFile(title: string, filterName: string, filterExt: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_file", { title, filterName, filterExt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickDirectory(title: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_directory", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(name: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorkspaceVariables(workspacePath: string, variables: Variable[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workspace_variables", { workspacePath, variables }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollectionVariables(collectionPath: string, variables: Variable[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection_variables", { collectionPath, variables }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEnvironmentVariables(collectionPath: string, environmentName: string, variables: Variable[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_environment_variables", { collectionPath, environmentName, variables }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getResolvedVariables(workspacePath: string | null, collectionPath: string | null, environmentName: string | null) : Promise<Result<{ [key in string]: ResolvedVariable }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_resolved_variables", { workspacePath, collectionPath, environmentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewTemplate(text: string, workspacePath: string | null, collectionPath: string | null, environmentName: string | null) : Promise<Result<PreviewResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_template", { text, workspacePath, collectionPath, environmentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCollectionManifest(path: string) : Promise<Result<Collection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_collection_manifest", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkspaceManifest(path: string) : Promise<Result<WorkspaceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workspace_manifest", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthRef = ({ [key in string]: string }) & { type: string }
/**
 * Represents a loaded collection.
 */
export type Collection = { path: string; manifest: CollectionManifest; environments: EnvironmentFile[]; items: CollectionItem[] }
export type CollectionItem = { type: "Request"; data: RequestFileWrapper } | { type: "Folder"; data: Folder }
/**
 * Represents the structure of a `cortex.yaml` collection manifest file.
 */
export type CollectionManifest = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the collection
 */
name: string; 
/**
 * Optional description of the collection
 */
description?: string | null; 
/**
 * Default authentication settings for all requests in the collection
 */
auth?: AuthRef | null; 
/**
 * Default headers for all requests in the collection
 */
headers?: { [key in string]: string } | null; 
/**
 * Collection-level variables
 */
variables?: Variable[] | null }
export type EnvironmentFile = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the environment
 */
name: string; 
/**
 * List of environment variables
 */
variables: Variable[] }
export type Folder = { name: string; path: string; relative_path: string; items: CollectionItem[] }
export type GreetResponse = { message: string }
export type PreviewResponse = { text: string; warnings: UnresolvedVariableWarning[] }
export type RequestBody = { text: string } | { json: string } | { form: { [key in string]: string } }
/**
 * Represents the structure of a `.crx` request file.
 */
export type RequestFile = { 
/**
 * Schema version (e.g., "1")
 */
version: string; 
/**
 * Human-readable name of the request
 */
name: string; 
/**
 * HTTP method (e.g., GET, POST, PUT, DELETE)
 */
method: string; 
/**
 * Request URL (may contain environment variables)
 */
url: string; 
/**
 * HTTP headers
 */
headers?: { [key in string]: string } | null; 
/**
 * Query parameters
 */
params?: { [key in string]: string } | null; 
/**
 * Request body
 */
body?: RequestBody | null; 
/**
 * Authentication configuration
 */
auth?: AuthRef | null; 
/**
 * Pre-request and post-response scripts
 */
scripts?: Scripts | null; 
/**
 * Test scripts
 */
tests?: string | null; 
/**
 * Tags for categorization
 */
tags?: string[] | null; 
/**
 * Per-request settings
 */
settings?: Settings | null }
export type RequestFileWrapper = { name: string; path: string; relative_path: string; content: RequestFile | null; error: string | null }
export type ResolvedVariable = { value: string; scope: VariableScope; secret: boolean }
export type Scripts = { pre?: string | null; post?: string | null }
export type Settings = { timeout?: number | null }
export type UnresolvedVariableWarning = { name: string }
export type Variable = { name: string; value: string; secret?: boolean; enabled?: boolean }
export type VariableScope = "global" | "collection" | "environment" | "runtime"
export type WorkspaceCollectionResult = { path: string; name: string | null; error: string | null }
export type WorkspaceResponse = { name: string; collections: WorkspaceCollectionResult[]; variables: Variable[] | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
